AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ECSALBListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
      - Type: forward
        TargetGroupArn:
          Fn::ImportValue: 'ECSTargetGroup'
      Conditions:
      - Field: path-pattern
        Values:
        - /
      ListenerArn:
        Fn::ImportValue: 'ALBListener'
      Priority: 1
