AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  DBUser:
    Type: String
    Description: DBUser
  DBPassword:
    Type: String
    Description: DBPassword
Resources:
  DBSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !ImportValue Vpc1
      CidrBlock: 10.0.10.0/24
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: !Ref "AWS::Region"
  DBSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !ImportValue Vpc1
      CidrBlock: 10.0.11.0/24
      AvailabilityZone:
        Fn::Select:
          - 1
          - Fn::GetAZs: !Ref "AWS::Region"
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: DB Security Group
      VpcId: !ImportValue Vpc1
  DBSecurityGroupMySQL:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref 'DBSecurityGroup'
      IpProtocol: tcp
      FromPort: '3306'
      ToPort: '3306'
      SourceSecurityGroupId:
        Fn::ImportValue: 'EcsSecurityGroup'
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: DBSubnetGroup
      SubnetIds:
      - !Ref DBSubnet1
      - !Ref DBSubnet2
  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: DBMySQL
      AllocatedStorage: 5
      DBInstanceClass: db.t2.micro
      Engine: "MySQL"
      EngineVersion: "5.6"
      MasterUsername:
        Ref: "DBUser"
      MasterUserPassword:
        Ref: "DBPassword"
      DBSubnetGroupName: !Ref 'DBSubnetGroup'
      VPCSecurityGroups:
      - !Ref 'DBSecurityGroup'
      Tags:
      -
        Key: "Name"
        Value: "MySQL Database"
    DeletionPolicy: "Snapshot"
Outputs:
  securityGroup:
    Value: !Ref 'DBSecurityGroup'
    Export:
      Name: DBSecurityGroup
  dbsubnet1:
    Value: !Ref 'DBSubnet1'
    Export:
      Name: DBSubnet1
  dbsubnet2:
    Value: !Ref 'DBSubnet2'
    Export:
      Name: DBSubnet2
