AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the ECS instances.
  ClusterName:
    Type: String
    Default: ECSCluster
    Description: A name for the cluster.
Resources:
  ECSSecurityGroupALBports:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId:
        Fn::ImportValue: ECSSecurityGroup
      IpProtocol: tcp
      FromPort: '31000'
      ToPort: '61000'
      SourceSecurityGroupId:
        Fn::ImportValue: ECSSecurityGroup
  ECSAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
      - Fn::ImportValue: Subnet1
      LaunchConfigurationName: !Ref 'ECSInstances'
      MinSize: '1'
      MaxSize: '1'
      DesiredCapacity: '1'
      TargetGroupARNs:
      - Fn::ImportValue: default-tg
      Tags:
      - Key: Name
        Value: ecs-container
        PropagateAtLaunch: true
  ECSInstances:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: ami-f63f6f91
      InstanceType: t2.micro
      IamInstanceProfile:
        Fn::ImportValue: ECSInstanceProfile
      AssociatePublicIpAddress: true
      KeyName: !Ref 'KeyName'
      SecurityGroups:
      - Fn::ImportValue: ECSSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          echo ECS_CLUSTER=${ClusterName} >> /etc/ecs/ecs.config
          yum install -y aws-cfn-bootstrap
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --region ${AWS::Region}
