AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: "ECSCluster"
Outputs:
  ECSCluster:
    Value: !Ref 'ECSCluster'
    Export:
      Name: 'ECSCluster'
