AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ECSRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ecsRole
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [ec2.amazonaws.com]
          Action: ['sts:AssumeRole']
      Path: /
      Policies:
      - PolicyName: ecs-service
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
              - 'ecs:CreateCluster'
              - 'ecs:DeregisterContainerInstance'
              - 'ecs:DiscoverPollEndpoint'
              - 'ecs:Poll'
              - 'ecs:RegisterContainerInstance'
              - 'ecs:StartTelemetrySession'
              - 'ecs:Submit*'
              - 'logs:CreateLogStream'
              - 'logs:PutLogEvents'
            Resource: '*'
  ECSServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ecsServiceRole
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [ecs.amazonaws.com]
          Action: ['sts:AssumeRole']
      Path: /
      Policies:
      - PolicyName: ecs-service
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
            - 'elasticloadbalancing:DeregisterInstancesFromLoadBalancer'
            - 'elasticloadbalancing:DeregisterTargets'
            - 'elasticloadbalancing:Describe*'
            - 'elasticloadbalancing:RegisterInstancesWithLoadBalancer'
            - 'elasticloadbalancing:RegisterTargets'
            - 'ec2:Describe*'
            - 'ec2:AuthorizeSecurityGroupIngress'
            Resource: '*'
  ECSInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
      - !Ref 'ECSRole'
Outputs:
  ECSRole:
    Value: !Ref 'ECSRole'
    Export:
      Name: ecsRole
  ECSServiceRole:
    Value: !Ref 'ECSServiceRole'
    Export:
      Name: ecsServiceRole
  ECSInstanceProfile:
    Value: !Ref 'ECSInstanceProfile'
    Export:
      Name: ECSInstanceProfile